//
// Created by Brandon Garling on 9/20/2016.
//

#ifndef CS430_PROJECT_2_BASIC_RAYCASTER_CONSTANTS_H
#define CS430_PROJECT_2_BASIC_RAYCASTER_CONSTANTS_H

#define TRUE 1
#define FALSE 0
#define LOG_LEVEL 2
#define INITIAL_BUFFER_SIZE 64

#endif //CS430_PROJECT_2_BASIC_RAYCASTER_CONSTANTS_H